### ISSUE TITLE
fixes 

### ISSUE THREAD

**Issue by djnighti** [sisaha9/razor_imu_9dof#1]
Here is a mod of your ros2 driver tested on the artemis openlog to make it run!! Thanks 👍 
[imu_node.txt](https://github.com/sisaha9/razor_imu_9dof/files/8400968/imu_node.txt)

**Comment by djnighti** [comment]
after your corrections, node published fine! This issue is now closed!

**Comment by sisaha9** [comment]
Thanks @djnighti for your contribution

**Comment by djnighti** [comment]
FYI I tested with Foxy on your galactic branch!
